[target.x86_64-pc-windows-gnullvm]
linker = "D:\\tools\\rust\\rustup\\toolchains\\stable-x86_64-pc-windows-gnullvm\\lib\\rustlib\\x86_64-pc-windows-gnullvm\\bin\\rust-lld.exe"
rustflags = [
  "-Lnative=D:\\tools\\rust\\rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\self-contained"
]

[target.x86_64-pc-windows-msvc]
rustflags = [
  "-Lnative=D:\\VSBuildTools\\VC\\Tools\\MSVC\\14.44.35207\\lib\\x64",
  "-Lnative=C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\x64",
  "-Lnative=C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\x64"
]
